### ISSUE TITLE
How to test on custom data?

### ISSUE THREAD

**Issue by visonpon** [ChaoyueSong/3d-corenet#2]
Hi, @ChaoyueSong , thanks for sharing this wonderful work, and I have tried to test it on some mesh files generated from other smpl based model, e.g,VIBE and so on, but the results are bad. 
So can you give some details on how to test on custom data? thanks~

**Comment by ChaoyueSong** [comment]
Hi, thanks for your interest!

When testing on new data, you can simply use test.py to achieve it. Don't forget to change the vertex_num and remove PMD calculation after reading the input meshes.

The performance is not very satisfactory on VIBE because of the limited generalization. The pre-trained model is trained with very simple poses in SMPL. We suggest that you can try to retrain the model on more complex poses in other datasets, e.g., SMPL-X, STAR, etc.
